name: CheckApiLimits

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  limits:

    runs-on: ubuntu-latest

    steps:
    - name: Check limits 
      env:
        NEKOWEB_API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
      run: |
        ls
