name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  update-website:
    runs-on: ubuntu-latest
    env:
        NEKOWEB_API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f update/requirements.txt ]; then pip install -r update/requirements.txt; fi
    - name: Run update script
      run: |
        python update/update.py
  update-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Update commit file
      run: |
        git rev-parse HEAD > 'update/last_commit.txt'
        cat update/last_commit.txt
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add update/last_commit.txt
        git commit -m "[skip ci]: Updated commit file"
        git push origin main
